### ISSUE TITLE
Onboarding checklist for new members of Hughes Lab

### ISSUE THREAD

**Issue by michaelchughes** [tufts-ml/hugheslab-onboarding#1]
By end of first day or so, you should:
* [ ] Create github account (or use existing one) and get added to HughesLab team <https://github.com/orgs/tufts-ml/teams/hugheslab/members>
-- We recommend you use a *professional* username. 

* [ ] Add yourself to the lab directory
-- <https://docs.google.com/spreadsheets/d/1PVeq1UmwchsMTx9nH7qZPmwcrxaMmquSHDlinAnB-zM/edit?usp=sharing>
-- Request edit access please

* [ ] Make sure you are added to the HughesLab meeting calendar (shared spreadsheets on Google Sheets)
-- <https://docs.google.com/spreadsheets/d/1_0Y0HO9j6bPhH3jp-sks3ftw246SMlvtgJjqv0t9alY/edit?usp=sharing>
-- Request edit access please

* [ ] Ask Mike for an invite to Slack and introduce yourself in #hugheslab-onboarding

* [ ] Apply for access to the HPC cluster at Tufts
-- See instructions here: https://github.com/tufts-ml/hugheslab-onboarding/blob/master/README.md

* [ ] Ask Mike if there are any specific IRB approvals or CITI trainings you should begin for your project
